// Structural gap heuristics over v4. Flags domains that look under-developed and
// theme keywords that have no dedicated domain. Writes v5/derived/audit-gaps.md.
// These are HINTS for the gaps change-set, not defects on their own.
import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { loadDomTree, flatten } from './lib.mjs';

const DERIVED = fileURLToPath(new URL('../derived/', import.meta.url));
mkdirSync(DERIVED, { recursive: true });

const { roots } = loadDomTree();
const all = flatten(roots);
const haystack = all
  .map((d) => `${d.name} ${d.description} ${d.questions.map((q) => q.question + ' ' + (q.exampleWords || '')).join(' ')}`)
  .join('\n')
  .toLowerCase();

// Modern-world themes that a contemporary list should cover. For each, whether
// the keyword appears anywhere, and whether any *domain name* owns it.
const THEMES = [
  'internet', 'website', 'email', 'software', 'app', 'smartphone', 'mobile phone',
  'social media', 'password', 'mobile money', 'bank card', 'plastic', 'recycling',
  'pollution', 'climate', 'refugee', 'election', 'vote', 'ngo', 'vaccine',
  'electricity', 'solar', 'battery', 'photograph', 'computer',
];
const nameOwns = (kw) => all.some((d) => d.name.toLowerCase().includes(kw));

const themeRows = THEMES.map((kw) => ({
  theme: kw,
  appearsAnywhere: haystack.includes(kw),
  ownedByDomainName: nameOwns(kw),
}));

// Under-developed domains: leaf domains (no children) with zero questions, or
// with very few example words overall.
const leaves = all.filter((d) => !d.children?.length);
const noQuestions = leaves.filter((d) => d.questions.length === 0);
const thinWords = leaves.filter((d) => {
  const w = d.questions.reduce((n, q) => n + (q.exampleWords ? q.exampleWords.split(',').length : 0), 0);
  return d.questions.length > 0 && w < 3;
});

const md = [];
md.push('# Structural gap audit (v4)', '');
md.push('Auto-generated by `v5/scripts/audit-gaps.mjs`. Hints for the gaps change-set.', '');
md.push('## Modern-theme coverage', '');
md.push('| theme | appears anywhere | owned by a domain name |', '|---|---|---|');
for (const r of themeRows) md.push(`| ${r.theme} | ${r.appearsAnywhere ? 'yes' : '**NO**'} | ${r.ownedByDomainName ? 'yes' : '**no**'} |`);
md.push('');
md.push(`## Leaf domains with no questions (${noQuestions.length})`, '');
for (const d of noQuestions) md.push(`- ${d.code} ${d.name}`);
md.push('');
md.push(`## Leaf domains with <3 example words total (${thinWords.length})`, '');
for (const d of thinWords) md.push(`- ${d.code} ${d.name}`);
md.push('');

writeFileSync(DERIVED + 'audit-gaps.md', md.join('\n'));
const missingThemes = themeRows.filter((r) => !r.ownedByDomainName).map((r) => r.theme);
console.log(`Gap audit: ${missingThemes.length} themes with no owning domain, ${noQuestions.length} empty leaves, ${thinWords.length} thin leaves -> derived/audit-gaps.md`);
console.log('  themes lacking a domain: ' + missingThemes.join(', '));
